from pathlib import Path
from playwright.sync_api import sync_playwright
import json
import os
ROOT = Path(__file__).resolve().parents[2]
ARTIFACTS = ROOT / 'BuildLogs' / 'browser'
ARTIFACTS.mkdir(parents=True, exist_ok=True)
results=[]
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,executable_path=os.environ.get('PLAYWRIGHT_CHROMIUM_EXECUTABLE'),args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1440,'height':1120},device_scale_factor=1)
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.set_content((ROOT / 'RelayBar_Preview.html').read_text())
    def check(name,value):
        assert value,name
        results.append('PASS: '+name)
    check('default project Hearth',page.locator('#barProject').inner_text()=='Hearth')
    check('default action Next slice',page.locator('#smart1').inner_text()=='Next slice')
    page.locator('[data-sample="error"]').click()
    check('error suggests Diagnose',page.locator('#smart1').inner_text()=='Diagnose')
    page.locator('#smart1').click()
    check('diagnostic packet rendered','Diagnose' in page.locator('#draft').input_value())
    page.locator('#handoff').click()
    check('handoff changes target',page.locator('#barTarget').inner_text()=='Claude')
    check('handoff carries evidence boundary','UNVERIFIED' in page.locator('#draft').input_value())
    page.locator('#task').fill('Scope only the entrance transition.')
    check('task edits invalidate previous draft',page.locator('#draft').input_value()=='')
    page.locator('#mode').select_option('Writing')
    check('mode overrides error heuristics',page.locator('#smart1').inner_text()=='Tighten')
    page.locator('#mode').select_option('Auto')
    page.locator('[data-sample="code"]').click()
    check('code suggests Explain',page.locator('#smart1').inner_text()=='Explain')
    page.locator('[data-id="bindery"]').click()
    check('project change clears reference',page.locator('#reference').input_value()=='')
    check('project change clears task',page.locator('#task').input_value()=='')
    page.locator('[data-id="hearth"]').click()
    page.locator('[data-sample="prose"]').click()
    check('prose suggests Tighten',page.locator('#smart1').inner_text()=='Tighten')
    page.locator('#mode').select_option('Build')
    page.locator('#smart1').click()
    with page.expect_download() as d:
        page.locator('#save').click()
    path=(ARTIFACTS / 'checkpoint.json')
    d.value.save_as(path)
    packet=json.loads(path.read_text())
    check('checkpoint contains correct schema',packet['schemaVersion']==1)
    check('checkpoint contains reviewed draft',packet['draft']['text']==page.locator('#draft').input_value())
    check('checkpoint contains provenance',packet['capture']['origin']=='Synthetic browser demonstration')
    page.on('dialog',lambda dialog:dialog.accept())
    page.locator('#clear').click()
    page.locator('#file').set_input_files(str(path))
    page.wait_for_function("document.getElementById('draft').value.includes('Next slice')")
    check('checkpoint restores draft','Next slice' in page.locator('#draft').input_value())
    page.screenshot(path=str(ARTIFACTS / 'Preview_Desktop.png'),full_page=True)
    page.locator('#reference').fill('x'*24001)
    page.locator('#compose').click()
    check('oversize reference blocked','exceeds 24,000' in page.locator('#status').inner_text())
    page.locator('#clear').click()
    page.locator('#reference').fill('<img src=x onerror=alert(1)>')
    page.locator('#compose').click()
    check('reference rendered as inert text',page.locator('#draft').input_value().find('<img')>=0)
    check('no script-injected image created',page.locator('img').count()==0)
    check('no JavaScript exceptions',not errors)
    page.set_viewport_size({'width':390,'height':844})
    page.screenshot(path=str(ARTIFACTS / 'Preview_Mobile.png'),full_page=True)
    check('narrow preview has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
    browser.close()
(ARTIFACTS / 'BROWSER_TEST_RESULTS.txt').write_text('\n'.join(results)+'\n\nBrowser tests only; not native macOS or Touch Bar tests.\n')
print('\n'.join(results));print(len(results),'checks passed')
